### ISSUE TITLE
Nothing but Black

### ISSUE THREAD

**Issue by stevel4857** [MozVR/panorama-viewer#3]
Hi, No complaints really (it's free after all) but it doesn't display in a non VR mode. All I see is black. I see numerous examples of VR where it displays in 2D and you either click a button or use ctrl+v to go into and out of VR mode. I believe it really needs to be this way both for backward compatibility to older 2D and ease of work, meaning I can work in 2D when I'm in a hurry. Just a thought.

**Comment by hh3m** [comment]
I absolutely agree. Just a simple check using THREE.js' Detector.js would be enough I guess:

<code>var renderer = Detector.webgl? new THREE.WebGLRenderer({ antialias: true }): new THREE.CanvasRenderer();</code>

**Comment by caseyyee** [comment]
There has been some breakage over the last week that could have caused the issues you have been seeing.  It should all work (including being compatible with non-VR browsers) now!

**Comment by caseyyee** [comment]
Closing for now.   Re-open if you continue to see problems.
